#!/usr/bin/env bash
set -e

# Telegram / Bot
echo "BOT_TOKEN=${BOT_TOKEN}" >> $GITHUB_ENV
echo "DEV_DRY_RUN=${DEV_DRY_RUN:-0}" >> $GITHUB_ENV
echo "HEALTH_PORT=${HEALTH_PORT:-8080}" >> $GITHUB_ENV
echo "ADMIN_ID=${ADMIN_ID}" >> $GITHUB_ENV
echo "ADMIN_USER_IDS=${ADMIN_USER_IDS}" >> $GITHUB_ENV

# Database / Logging / TZ
echo "DB_URL=${DB_URL:-sqlite+aiosqlite:///./var/bot.db}" >> $GITHUB_ENV
echo "MIGRATE_ON_START=${MIGRATE_ON_START:-true}" >> $GITHUB_ENV
echo "TIMEZONE=${TIMEZONE:-Europe/Moscow}" >> $GITHUB_ENV
echo "LOG_LEVEL=${LOG_LEVEL:-INFO}" >> $GITHUB_ENV
echo "LOG_DIR=${LOG_DIR:-logs}" >> $GITHUB_ENV

# Commerce / Leads
echo "VELAVIE_URL=${VELAVIE_URL}" >> $GITHUB_ENV
echo "VILAVI_REF_LINK_DISCOUNT=${VILAVI_REF_LINK_DISCOUNT}" >> $GITHUB_ENV
echo "VILAVI_ORDER_NO_REG=${VILAVI_ORDER_NO_REG}" >> $GITHUB_ENV
echo "BASE_REGISTER_URL=${BASE_REGISTER_URL}" >> $GITHUB_ENV
echo "LEADS_CHAT_ID=${LEADS_CHAT_ID}" >> $GITHUB_ENV

# Tribute
echo "RUN_TRIBUTE_WEBHOOK=${RUN_TRIBUTE_WEBHOOK:-false}" >> $GITHUB_ENV
echo "TRIBUTE_PORT=${TRIBUTE_PORT:-8080}" >> $GITHUB_ENV
echo "TRIBUTE_API_KEY=${TRIBUTE_API_KEY}" >> $GITHUB_ENV
echo "TRIBUTE_LINK_BASIC=${TRIBUTE_LINK_BASIC}" >> $GITHUB_ENV
echo "TRIBUTE_LINK_PRO=${TRIBUTE_LINK_PRO}" >> $GITHUB_ENV
echo "SUB_BASIC_PRICE=${SUB_BASIC_PRICE}" >> $GITHUB_ENV
echo "SUB_PRO_PRICE=${SUB_PRO_PRICE}" >> $GITHUB_ENV

# Feature flags
echo "DEBUG_COMMANDS=${DEBUG_COMMANDS:-false}" >> $GITHUB_ENV
echo "FF_FLOODWAIT_PATCH=${FF_FLOODWAIT_PATCH:-true}" >> $GITHUB_ENV

# Assets
echo "IMAGES_MODE=${IMAGES_MODE:-catalog_remote}" >> $GITHUB_ENV
echo "IMAGES_BASE=${IMAGES_BASE}" >> $GITHUB_ENV
echo "IMAGES_DIR=${IMAGES_DIR:-app/static/images/products}" >> $GITHUB_ENV
echo "QUIZ_IMAGE_MODE=${QUIZ_IMAGE_MODE:-remote}" >> $GITHUB_ENV
echo "QUIZ_IMG_BASE=${QUIZ_IMG_BASE}" >> $GITHUB_ENV

# Stage / Prod matrix
echo "STAGE_MEDIA_REF=${STAGE_MEDIA_REF}" >> $GITHUB_ENV
echo "STAGE_IMAGES_BASE=${STAGE_IMAGES_BASE}" >> $GITHUB_ENV
echo "STAGE_QUIZ_IMG_BASE=${STAGE_QUIZ_IMG_BASE}" >> $GITHUB_ENV
echo "STAGE_SENTRY_DSN=${STAGE_SENTRY_DSN}" >> $GITHUB_ENV
echo "STAGE_SENTRY_TRACES_SAMPLE_RATE=${STAGE_SENTRY_TRACES_SAMPLE_RATE}" >> $GITHUB_ENV

echo "PROD_MEDIA_REF=${PROD_MEDIA_REF}" >> $GITHUB_ENV
echo "PROD_IMAGES_BASE=${PROD_IMAGES_BASE}" >> $GITHUB_ENV
echo "PROD_QUIZ_IMG_BASE=${PROD_QUIZ_IMG_BASE}" >> $GITHUB_ENV
echo "PROD_SENTRY_DSN=${PROD_SENTRY_DSN}" >> $GITHUB_ENV
echo "PROD_SENTRY_TRACES_SAMPLE_RATE=${PROD_SENTRY_TRACES_SAMPLE_RATE}" >> $GITHUB_ENV

# Planner / Storage / Codex / Notify
echo "AI_PLAN_MODEL=${AI_PLAN_MODEL:-gpt-4o-mini}" >> $GITHUB_ENV
echo "WEEKLY_PLAN_CRON=${WEEKLY_PLAN_CRON:-mon@10}" >> $GITHUB_ENV
echo "PLAN_ARCHIVE_DIR=${PLAN_ARCHIVE_DIR:-var/plans}" >> $GITHUB_ENV
echo "USE_REDIS=${USE_REDIS:-0}" >> $GITHUB_ENV
echo "REDIS_URL=${REDIS_URL}" >> $GITHUB_ENV

echo "CODEX_SHARED_KEY=${CODEX_SHARED_KEY}" >> $GITHUB_ENV
echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" >> $GITHUB_ENV
echo "TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}" >> $GITHUB_ENV
echo "SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}" >> $GITHUB_ENV
