#!/usr/bin/env bash
set -e

# Telegram / Bot
echo "BOT_TOKEN=${BOT_TOKEN}" >> $GITHUB_ENV
echo "DEV_DRY_RUN=${DEV_DRY_RUN:-0}" >> $GITHUB_ENV
echo "HEALTH_PORT=${HEALTH_PORT:-8080}" >> $GITHUB_ENV
echo "ADMIN_ID=${ADMIN_ID}" >> $GITHUB_ENV
echo "ADMIN_USER_IDS=${ADMIN_USER_IDS}" >> $GITHUB_ENV

# Database / Logging
echo "DB_URL=${DB_URL:-sqlite+aiosqlite:///./var/bot.db}" >> $GITHUB_ENV
echo "MIGRATE_ON_START=${MIGRATE_ON_START:-true}" >> $GITHUB_ENV
echo "TIMEZONE=${TIMEZONE:-Europe/Moscow}" >> $GITHUB_ENV
echo "LOG_LEVEL=${LOG_LEVEL:-INFO}" >> $GITHUB_ENV
echo "LOG_DIR=${LOG_DIR:-logs}" >> $GITHUB_ENV

# Commerce / Assets / Planner / Storage / Codex etc.
echo "VELAVIE_URL=${VELAVIE_URL}" >> $GITHUB_ENV
echo "VILAVI_REF_LINK_DISCOUNT=${VILAVI_REF_LINK_DISCOUNT}" >> $GITHUB_ENV
echo "VILAVI_ORDER_NO_REG=${VILAVI_ORDER_NO_REG}" >> $GITHUB_ENV
echo "BASE_REGISTER_URL=${BASE_REGISTER_URL}" >> $GITHUB_ENV
echo "IMAGES_BASE=${IMAGES_BASE}" >> $GITHUB_ENV
echo "QUIZ_IMG_BASE=${QUIZ_IMG_BASE}" >> $GITHUB_ENV
echo "CODEX_SHARED_KEY=${CODEX_SHARED_KEY}" >> $GITHUB_ENV
echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" >> $GITHUB_ENV
echo "TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}" >> $GITHUB_ENV
echo "SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}" >> $GITHUB_ENV
