[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true
known_first_party = ["app", "tools", "tests"]

[tool.ruff]
line-length = 100
target-version = "py311"
fix = true

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "SIM"]

[tool.ruff.lint.isort]
known-first-party = ["app", "tools", "tests"]
combine-as-imports = true
