global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "five-keys-bot"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - bot:8080
