name: weekly-deps-update

on:
  schedule:
    - cron: "0 6 * * MON"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  BOT_TOKEN: dummy:000
  SERVICE_HOST: 127.0.0.1
  HEALTH_PORT: 0
  NO_NET: 0
  MPLBACKEND: Agg
  MEDIA_OWNER: go2telegram
  MEDIA_REPO: media
  MEDIA_REF: 1312d74492d26a8de5b8a65af38293fe6bf8ccc5

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run deps auto update
        id: update
        shell: bash
        run: |
          python tools/deps_auto_pr.py
          DRAFT=$(python - <<'PY'
import json
from pathlib import Path
meta = json.loads(Path('build/reports/auto_update_meta.json').read_text())
print(1 if (meta["security_exit"] != 0 or meta["tests_exit"] != 0) else 0)
PY
          )
          echo "DRAFT=$DRAFT" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(deps): weekly update"
          body-path: build/reports/auto_update_body.md
          commit-message: "chore(deps): weekly update via pip-tools"
          branch: chore/weekly-deps-update
          labels: >
            deps,autoupdate${{ steps.update.outputs.DRAFT == '1' && ',needs-review,security/high' || '' }}
          draft: ${{ steps.update.outputs.DRAFT == '1' }}
          signoff: true
          delete-branch: true
