name: auto_label

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  pull-requests: write

jobs:
  add-automerge-label:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Resolve PR number (by head or commit)
        id: prnum
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            // 1) PR, который запустил workflow (обычный кейс)
            const headRef = process.env.GITHUB_HEAD_REF || context.ref.replace('refs/heads/','');
            let number = "";

            if (headRef) {
              const { data } = await github.rest.pulls.list({
                owner, repo, head: `${owner}:${headRef}`, state: 'open'
              });
              if (data.length) number = String(data[0].number);
            }

            // 2) Fallback: PR, связанный с текущим SHA
            if (!number) {
              const res = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner, repo, commit_sha: context.sha
              });
              if (res.data.length) number = String(res.data[0].number);
            }

            core.setOutput('number', number);
            if (!number) core.info('PR not found for this context (head/SHA).');

      - name: Exit if no PR
        if: steps.prnum.outputs.number == ''
        run: echo "No PR for this CI run" && exit 0

      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/pull/${{ steps.prnum.outputs.number }}/head

      - name: Paths filter (risky changes)
        id: pf
        uses: dorny/paths-filter@v3
        with:
          filters: |
            risky:
              - '.github/workflows/**'
              - 'Dockerfile'
              - 'requirements*.txt'
              - 'run.py'
              - 'app/main.py'
              - 'scripts/**'

      - name: Get PR author
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const {data: pr} = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number("${{ steps.prnum.outputs.number }}"),
            });
            core.setOutput('author', pr.user.login);

      - name: Add 'automerge' label (native)
        if: |
          steps.pf.outputs.risky != 'true' &&
          (steps.pr.outputs.author == 'go2telegram' || steps.pr.outputs.author == 'github-actions[bot]')
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const number = Number("${{ steps.prnum.outputs.number }}");
            await github.rest.issues.addLabels({ owner, repo, issue_number: number, labels: ['automerge'] });
            core.info(`Label 'automerge' added to PR #${number}`);

      - name: Upload debug (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-auto_label-${{ github.run_id }}
          path: debug.log
          if-no-files-found: ignore
