name: CI / workflows-lint
on:
  pull_request:
    paths: ['.github/workflows/**/*.yml']
  push:
    branches: ['main']
    paths:   ['.github/workflows/**/*.yml']
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          fail_on_error: true
          reporter: github-check
