name: CI / workflow-lint

on:
  pull_request:
    paths:
      - ".github/workflows/**/*.yml"
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/**/*.yml"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-review
          level: error
