name: CI

on:
  push:
    branches:
      - main
      - integration/**
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Build catalog artifacts
        run: make build-products
      - name: Validate catalog
        run: make validate-products
      - name: Run tests
        run: pytest
      - name: Repository audit
        run: tools/audit_repo.sh
