name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      BOT_TOKEN: dummy:000
      SERVICE_HOST: 127.0.0.1
      HEALTH_PORT: 0
      NO_NET: 0
      PYTHONWARNINGS: ignore
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
          pip install pytest pytest-asyncio pytest-cov
      - name: Build catalog (online)
        run: |
          python tools/build_products.py build
          python tools/build_products.py validate
      - name: Head check media (warning only)
        run: python tools/head_check.py
      - name: Self audit (fast)
        run: python tools/self_audit.py --fast --no-net --out build/reports/self_audit.md
      - name: Self audit (ci)
        run: python tools/self_audit.py --fast --no-net --ci --out build/reports/self_audit_ci.md
      - name: Tests
        run: pytest -q
      - name: Validate PR readiness
        run: |
          python tools/self_audit.py --fast --no-net --ci --out build/reports/self_audit_final.md
          echo "::notice file=build/reports/self_audit_final.md::Self audit summary"
      - uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: build/reports/*
