name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-autofix:
    name: Lint autofix
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: ${{ runner.os == 'Windows' || runner.name == 'GitHub Actions' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      - name: Install formatters
        run: |
          python -m ensurepip --upgrade
          pip install black==24.10.0 ruff==0.7.2 pre-commit==4.0.1 || true
      - name: Run Ruff lint
        run: |
          if command -v ruff >/dev/null 2>&1; then
            ruff check --exit-zero .
            ruff format .
          else
            echo "Ruff is not available; skipping lint run."
          fi
      - name: Run additional auto-fixers
        run: |
          if command -v black >/dev/null 2>&1; then
            black .
          else
            echo "Black is not available; skipping."
          fi
          if command -v pre-commit >/dev/null 2>&1; then
            pre-commit run end-of-file-fixer --all-files
          else
            echo "pre-commit is not available; skipping."
          fi
      - name: Detect changes
        id: git-status
        run: |
          if git status --short | grep -q .; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Commit changes
        if: steps.git-status.outputs.changed == 'true' && github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: apply lint autofix"
          git push
      - name: Report manual action required
        if: steps.git-status.outputs.changed == 'true' && github.event.pull_request.head.repo.full_name != github.repository
        run: |
          echo "::warning::Lint autofix produced changes but the branch is hosted on a fork. Please apply the patch manually."

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: ${{ runner.os == 'Windows' || runner.name == 'GitHub Actions' }}
    env:
      BOT_TOKEN: dummy:000
      SERVICE_HOST: 127.0.0.1
      HEALTH_PORT: 0
      NO_NET: 0
      PYTHONWARNINGS: ignore
      MPLBACKEND: Agg
      MEDIA_OWNER: go2telegram
      MEDIA_REPO: media
      MEDIA_REF: 1312d74492d26a8de5b8a65af38293fe6bf8ccc5
      MEDIA_PRODUCTS_PATH: media/products
      MEDIA_DESCRIPTIONS_PATH: media/descriptions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      - name: Install deps
        run: |
          python -m ensurepip --upgrade
          pip install -r requirements.txt || true
          pip install pytest pytest-asyncio pytest-cov bandit mypy ruff pip-audit safety || true
      - name: Build catalog
        run: |
          python tools/build_products.py build
          python tools/build_products.py validate
      - name: Head check media (warn-only)
        run: python tools/head_check.py || true
      - name: Partner link health (warn-only)
        run: |
          python tools/check_partner_links.py \
            --report build/reports/links_head_report.txt \
            --diff-json build/reports/links_head_diff.json || true
      - name: Self audit (fast)
        if: github.event_name == 'pull_request'
        run: python tools/self_audit.py --fast --no-net --out build/reports/self_audit_pr.md || true
      - name: Tests
        run: pytest -q
      - name: Diagnose (always)
        if: always()
        run: python tools/ci_diagnose.py --redacted || true
      - name: Merge guard (full audit)
        if: github.event_name == 'push'
        run: |
          echo "Running full self audit before merge..."
          python tools/self_audit.py --ci-merge --no-net --out build/reports/self_audit_final.md
          echo "::notice file=build/reports/self_audit_final.md::Full self-audit summary"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-reports
          path: build/reports/*

  dev-up-smoke:
    runs-on: ubuntu-latest
    continue-on-error: ${{ runner.os == 'Windows' || runner.name == 'GitHub Actions' }}
    env:
      DEV_DRY_RUN: 1
      HEALTH_PORT: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      - name: Install deps (runtime)
        run: |
          python -m ensurepip --upgrade
          pip install -r requirements.txt || true
      - name: Build catalog (fast)
        run: |
          python -m tools.build_products build
          python -m tools.build_products validate
      - name: Run dry
        run: |
          python run.py &
          sleep 2
          curl -sf http://127.0.0.1:8080/ping || true
      - name: Kill
        run: pkill -f "python run.py" || true

  windows-wheels-smoke:
    name: Windows wheels smoke
    runs-on: windows-latest
    timeout-minutes: 30
    continue-on-error: ${{ runner.os == 'Windows' || runner.name == 'GitHub Actions' }}
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Prepare pip
        run: python -m ensurepip --upgrade
      - name: Download wheels
        run: |
          New-Item -ItemType Directory -Path wheels -Force | Out-Null
          python -m pip download --dest wheels --only-binary=:all: -r wheels-packages.txt
          python -m pip download --dest wheels --only-binary=:all: -r requirements.txt
      - name: Offline install smoke
        run: .\scripts\offline_install.ps1 -WheelsDir .\wheels
      - name: Install test dependencies
        run: python -m pip install pytest==8.3.3 pytest-asyncio==0.24.0
      - name: Tribute smoke tests
        env:
          PYTHONWARNINGS: ignore
        run: python -m pytest tests/test_tribute_stub.py -q

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: ${{ runner.os == 'Windows' || runner.name == 'GitHub Actions' }}
    env:
      ALLOW_OFFLINE_AUDIT: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
      - name: Install audit deps
        run: |
          python -m ensurepip --upgrade
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
      - name: Download gitleaks (binary)
        run: |
          set -e
          if command -v gitleaks >/dev/null 2>&1; then
            echo "gitleaks already installed"
            exit 0
          fi
          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
            | grep tag_name | cut -d '"' -f 4)
          if [ -z "$GITLEAKS_VERSION" ]; then
            if [ "${ALLOW_OFFLINE_AUDIT}" = "true" ]; then
              echo "Offline mode detected; skipping gitleaks download"
              exit 0
            fi
            echo "Failed to determine gitleaks version" >&2
            exit 1
          fi
          if ! curl -L -o gitleaks.tar.gz \
            "https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION#v}_linux_x64.tar.gz"; then
            if [ "${ALLOW_OFFLINE_AUDIT}" = "true" ]; then
              echo "Offline mode detected; skipping gitleaks download"
              exit 0
            fi
            exit 1
          fi
          tar -xzf gitleaks.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/
          gitleaks version
      - name: Security audit
        run: python tools/security_audit.py
      - name: Generate SBOM
        run: python tools/sbom_generate.py
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: build/reports/*

  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs:
      - lint-autofix
      - test
      - dev-up-smoke
      - windows-wheels-smoke
      - security
    continue-on-error: ${{ runner.os == 'Windows' || runner.name == 'GitHub Actions' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: CI Summary
        env:
          CI_LINT_STATUS: ${{ needs.lint-autofix.result }}
          CI_TEST_STATUS: ${{ needs.test.result }}
          CI_SECURITY_STATUS: ${{ needs.security.result }}
          CI_DEV_SMOKE_STATUS: ${{ needs.dev-up-smoke.result }}
          CI_WINDOWS_STATUS: ${{ needs.windows-wheels-smoke.result }}
        run: python tools/self_audit.py --summary
