name: CI

on:
  push:
    branches:
      - main
      - integration/**
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Build catalog (online, strict 38/38)
        run: |
          python tools/build_products.py build \
            --descriptions-path "app/catalog/descriptions" \
            --images-base "https://raw.githubusercontent.com/go2telegram/media/1312d74492d26a8de5b8a65af38293fe6bf8ccc5/media/products" \
            --strict-images --strict-descriptions \
            --expect-count from=images --fail-on-mismatch
          python tools/build_products.py validate
      - name: Validate quiz assets
        run: python tools/validate_quiz_assets.py
      - name: HEAD check images (products & quizzes)
        run: python tools/head_check.py
      - name: Run tests
        run: pytest
      - name: Repository audit
        run: tools/audit_repo.sh
      - name: Secret audit
        run: python tools/audit_secrets.py
