name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: dummy:000
      SERVICE_HOST: 127.0.0.1
      HEALTH_PORT: 0
      NO_NET: 0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Build catalog (online)
        run: |
          python tools/build_products.py build
          python tools/build_products.py validate
      - name: Head check media (warning-only)
        run: python tools/head_check.py || true
      - name: Tests
        run: pytest -q
