name: CI

on:
  push:
  pull_request:

jobs:
  smoke:
    name: Smoke test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test
        run: HEALTH_PORT=8080 nohup python run.py & sleep 2 && bash tools/smoke.sh
