name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run basic checks
        run: |
          python -m compileall ml app jobs

      - name: Upload trained models
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trained-models-${{ github.sha }}
          path: artifacts/models/*.pkl
          if-no-files-found: ignore
