name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy bandit
      - name: Ruff
        run: ruff check .
      - name: Mypy
        run: mypy --config-file pyproject.toml
      - name: Bandit
        run: bandit -r app --confidence-level MEDIUM
      - name: Bytecode compilation
        run: |
          python -m compileall app
          python -m compileall doctor.py
