name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  PYTHONPATH: .

jobs:
  lint-autofix:
    name: Lint autofix
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Lint autofix
        run: |
          bash scripts/lint_autofix.sh

      - name: Auto-commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: apply black/isort"
          file_pattern: |
            **/*.py
            pyproject.toml
            scripts/lint_autofix.sh
          branch: ${{ github.head_ref }}

      - name: Lint check (strict)
        run: |
          pip install -q black==24.8.0 isort==5.13.2
          isort --profile black --check-only .
          black --check .

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NO_NET: 0
      PYTHONWARNINGS: ignore
      MPLBACKEND: Agg
      MEDIA_OWNER: go2telegram
      MEDIA_REPO: media
      MEDIA_REF: 1312d74492d26a8de5b8a65af38293fe6bf8ccc5
      MEDIA_PRODUCTS_PATH: media/products
      MEDIA_DESCRIPTIONS_PATH: media/descriptions
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap-env
      - name: Set test env defaults
        run: |
          echo "BOT_TOKEN=${BOT_TOKEN:-dummy:000}" >> $GITHUB_ENV
          echo "SERVICE_HOST=${SERVICE_HOST:-127.0.0.1}" >> $GITHUB_ENV
          echo "HEALTH_PORT=${HEALTH_PORT:-0}" >> $GITHUB_ENV
        env:
          BOT_TOKEN: dummy:000
          SERVICE_HOST: 127.0.0.1
          HEALTH_PORT: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov bandit mypy ruff pip-audit safety
      - name: Build catalog
        run: |
          python tools/build_products.py build
          python tools/build_products.py validate
      - name: Head check media (warn-only)
        run: python tools/head_check.py || true
      - name: Partner link health (warn-only)
        run: |
          python tools/check_partner_links.py \
            --report build/reports/links_head_report.txt \
            --diff-json build/reports/links_head_diff.json || true
      - name: Self audit (fast)
        if: github.event_name == 'pull_request'
        run: python tools/self_audit.py --fast --no-net --out build/reports/self_audit_pr.md || true
      - name: Tests
        run: pytest -q
      - name: Diagnose (always)
        if: always()
        run: python tools/ci_diagnose.py --redacted || true
      - name: Merge guard (full audit)
        if: github.event_name == 'push'
        run: |
          echo "Running full self audit before merge..."
          python tools/self_audit.py --ci-merge --no-net --out build/reports/self_audit_final.md
          echo "::notice file=build/reports/self_audit_final.md::Full self-audit summary"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-reports
          path: build/reports/*

  dev-up-smoke:
    runs-on: ubuntu-latest
    env:
      DEV_DRY_RUN: 1
      HEALTH_PORT: 0
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap-env
      - name: Set smoke env defaults
        run: echo "BOT_TOKEN=${BOT_TOKEN:-dummy:000}" >> $GITHUB_ENV
        env:
          BOT_TOKEN: dummy:000
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps (runtime)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build catalog (fast)
        run: |
          python -m tools.build_products build
          python -m tools.build_products validate
      - name: Local dev_check summary (fast)
        run: python -m tools.dev_check --fast --json || true
      - name: Run dry
        run: |
          python run.py &
          sleep 2
          curl -sf http://127.0.0.1:8080/ping || true
      - name: Kill
        run: pkill -f "python run.py" || true

  windows-wheels-smoke:
    name: Windows wheels smoke
    runs-on: windows-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Prepare pip
        run: python -m pip install --upgrade pip
      - name: Download wheels
        run: |
          New-Item -ItemType Directory -Path wheels -Force | Out-Null
          python -m pip download --dest wheels --only-binary=:all: -r wheels-packages.txt
          python -m pip download --dest wheels --only-binary=:all: -r requirements.txt
      - name: Offline install smoke
        run: .\scripts\offline_install.ps1 -WheelsDir .\wheels
      - name: Install test dependencies
        run: python -m pip install pytest==8.3.3 pytest-asyncio==0.24.0
      - name: Tribute smoke tests
        env:
          PYTHONWARNINGS: ignore
        run: python -m pytest tests/test_tribute_stub.py -q

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      SECURITY_FAIL_LEVEL: CRITICAL
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install audit deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Download gitleaks (binary)
        run: |
          set -e
          if command -v gitleaks >/dev/null 2>&1; then
            gitleaks version
            exit 0
          fi
          if ! curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest -o gitleaks_latest.json; then
            echo "Skipping gitleaks download (offline?)"
            exit 0
          fi
          GITLEAKS_VERSION=$(grep tag_name gitleaks_latest.json | cut -d '"' -f 4)
          if [ -z "$GITLEAKS_VERSION" ]; then
            echo "Skipping gitleaks download (version not detected)"
            exit 0
          fi
          if ! curl -L -o gitleaks.tar.gz \
            https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION#v}_linux_x64.tar.gz; then
            echo "Skipping gitleaks download (offline?)"
            exit 0
          fi
          tar -xzf gitleaks.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/
          gitleaks version
      - name: Security audit
        run: python tools/security_audit.py
      - name: Install CycloneDX CLI
        run: |
          pip install "cyclonedx-bom==7.1.*" || echo "CycloneDX not available, continuing"
      - name: Generate SBOM
        run: |
          python tools/sbom_generate.py || echo "⚠️ SBOM skipped (no cyclonedx-bom)"
        continue-on-error: false
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: build/reports/*
