name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      BOT_TOKEN: dummy:000
      SERVICE_HOST: 127.0.0.1
      HEALTH_PORT: 0
      NO_NET: 0
      PYTHONWARNINGS: ignore
      MPLBACKEND: Agg
      MEDIA_OWNER: go2telegram
      MEDIA_REPO: media
      MEDIA_REF: 1312d74492d26a8de5b8a65af38293fe6bf8ccc5
      MEDIA_PRODUCTS_PATH: media/products
      MEDIA_DESCRIPTIONS_PATH: media/descriptions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Build catalog
        run: |
          python tools/build_products.py build
          python tools/build_products.py validate
      - name: Head check media (warn-only)
        run: python tools/head_check.py || true
      - name: Self audit (fast)
        if: github.event_name == 'pull_request'
        run: python tools/self_audit.py --fast --no-net --out build/reports/self_audit_pr.md || true
      - name: Tests
        run: pytest -q
      - name: Diagnose (always)
        if: always()
        run: python tools/ci_diagnose.py --redacted || true
      - name: Merge guard (full audit)
        if: github.event_name == 'push'
        run: |
          echo "Running full self audit before merge..."
          python tools/self_audit.py --ci-merge --no-net --out build/reports/self_audit_final.md
          echo "::notice file=build/reports/self_audit_final.md::Full self-audit summary"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-reports
          path: build/reports/*

  security:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install audit deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Security audit
        run: python tools/security_audit.py
      - name: Generate SBOM
        run: python tools/sbom_generate.py
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: build/reports/*
