name: deploy
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Deploy to server (placeholder)
        run: |
          echo "Deploying version ${{ github.event.release.tag_name }}"
          # SSH/scp или API-запрос к хостингу
