name: nightly_load

on:
  schedule:
    - cron: '0 3 * * *'   # каждый день в 03:00 UTC
  workflow_dispatch:

jobs:
  render_all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB }}

      - name: Bootstrap env
        run: ./.github/scripts/bootstrap-env.sh
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CODEX_SHARED_KEY: ${{ secrets.CODEX_SHARED_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          IMAGES_BASE: ${{ vars.IMAGES_BASE }}
          QUIZ_IMG_BASE: ${{ vars.QUIZ_IMG_BASE }}
          HEALTH_PORT: ${{ vars.HEALTH_PORT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install mermaid-cli
        run: npm i -g @mermaid-js/mermaid-cli@10

      - name: Ensure Puppeteer config (no sandbox)
        run: |
          echo '{"args":["--no-sandbox","--disable-setuid-sandbox"]}' > docs/puppeteer.json

      - name: Render all *.mmd → *.svg
        run: |
          set -e
          for f in docs/menu_map.mmd docs/menu_map_flows.mmd docs/menu_map_admin.mmd; do
            if [ -f "$f" ]; then
              out="${f%.mmd}.svg"
              mmdc -p docs/puppeteer.json -i "$f" -o "$out" -b transparent -w 1400
              echo "✅ Rendered $out"
            else
              echo "⚠️ $f not found — skipping"
            fi
          done

      - name: Commit SVG if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/*.svg
          git diff --cached --quiet || git commit -m "chore(docs): nightly render menu maps"
          git push
