name: nightly_load

on:
  schedule:
    - cron: "0 3 * * *"   # каждый день в 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node (for mermaid-cli)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install mermaid-cli
        run: npm i -g @mermaid-js/mermaid-cli@10

      - name: Try render Mermaid
        id: render
        shell: bash
        run: |
          set -eo pipefail
          mkdir -p artifacts/menu
          if mmdc -i docs/menu_map.mmd -o artifacts/menu/menu_map.svg; then
            echo "failed=0" >> $GITHUB_OUTPUT
          else
            echo "failed=1" >> $GITHUB_OUTPUT
          fi

      - name: Auto-fix and retry (on render fail)
        if: steps.render.outputs.failed == '1'
        shell: bash
        run: |
          chmod +x scripts/auto_fix_and_retry.sh || true
          ./scripts/auto_fix_and_retry.sh docs/menu_map.mmd || true
          mmdc -i docs/menu_map.mmd -o artifacts/menu/menu_map.svg || true

      - name: Create PR if changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(menu): auto-fix Mermaid & refresh artifacts"
          title: "chore(menu): auto-fix Mermaid & refresh artifacts"
          body: |
            Nightly auto-fix: Mermaid render & artifacts refresh.
            - Файл: `docs/menu_map.mmd`
            - Артефакт: `artifacts/menu/menu_map.svg`
            - Скрипт: `scripts/auto_fix_and_retry.sh`
          branch: "menu-autofix-${{ github.run_id }}"
          base: "main"
          labels: "automerge"
          add-paths: |
            docs/menu_map.mmd
            artifacts/menu/**
