name: Nightly Render

on:
  schedule:
    - cron: "0 2 * * *"   # каждый день в 02:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-nightly"
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install system deps (fonts for Mermaid)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends fonts-noto fonts-noto-cjk fonts-noto-color-emoji
          sudo rm -rf /var/lib/apt/lists/*
      - name: Enable Corepack & install deps
        run: |
          corepack enable
          npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: Deploy
        uses: actions/deploy-pages@v4
