name: pages_probe
on:
  workflow_dispatch: {}
permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build tiny site
        run: |
          mkdir -p site
          cat > site/index.html <<'HTML'
          <!doctype html><meta charset="utf-8">
          <title>Pages OK</title>
          <h1>GitHub Pages is alive ✅</h1>
          <p>Repository: go2telegram/five_keys_mirror</p>
          HTML
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site
          name: github-pages
      - id: deploy
        uses: actions/deploy-pages@v4
      - run: echo "Probe URL: ${{ steps.deploy.outputs.page_url }}"
