name: pr_automerge

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    # Не трогаем PR без лейбла automerge + пускаем только доверенных авторов
    if: >
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      (github.event.pull_request.user.login == 'go2telegram' ||
       github.actor == 'github-actions[bot]')

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # 1) Фильтр «рискованных» путей: если что-то из списка тронуто — автомёрдж отключаем
      - name: Paths filter (risky changes)
        id: pf
        uses: dorny/paths-filter@v3
        with:
          filters: |
            risky:
              - '.github/workflows/**'
              - 'Dockerfile'
              - 'requirements*.txt'
              - 'run.py'
              - 'app/main.py'
              - 'scripts/**'

      # 2) Если были рискованные изменения — снимаем лейбл automerge (PR уйдет на ручной ревью)
      - name: Remove automerge label if risky
        if: steps.pf.outputs.risky == 'true'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'automerge'

      # 3) Авто-мердж безопасных PR когда все проверки зелёные
      - name: Auto-merge when checks are green
        if: steps.pf.outputs.risky != 'true'
        uses: peter-evans/auto-merge@v3
        with:
          merge-method: squash
