name: pr_automerge

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, ready_for_review, edited]
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: >
      (github.event_name == 'pull_request') &&
      contains(github.event.pull_request.labels.*.name, 'automerge') &&
      (github.event.pull_request.user.login == 'go2telegram' || github.actor == 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Paths filter (risky changes)
        id: pf
        uses: dorny/paths-filter@v3
        with:
          filters: |
            risky:
              - '.github/workflows/**'
              - 'Dockerfile'
              - 'requirements*.txt'
              - 'run.py'
              - 'app/main.py'
              - 'scripts/**'

      - name: Remove automerge label if risky
        if: steps.pf.outputs.risky == 'true'
        uses: actions-ecosystem/action-remove-labels@v1
        with: { labels: 'automerge' }

      - name: Auto-merge when checks are green
        if: steps.pf.outputs.risky != 'true'
        uses: peter-evans/auto-merge@v3
        with:
          merge-method: squash

      - name: Upload debug (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.workflow }}-${{ github.run_id }}
          path: |
            debug.log
          if-no-files-found: warn

  automerge_on_ci_complete:
    if: >
      github.event_name == 'workflow_run' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Resolve PR by SHA
        id: prnum
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const { data } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner, repo, commit_sha: context.sha
            });
            if (data.length) core.setOutput('number', String(data[0].number));
            else core.setOutput('number', '');

      - name: Exit if no PR
        if: steps.prnum.outputs.number == ''
        run: echo "No PR associated with CI run" && exit 0

      - name: Get PR JSON
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const {data: pr} = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number("${{ steps.prnum.outputs.number }}"),
            });
            core.setOutput('author', pr.user.login);
            core.setOutput('labels', JSON.stringify(pr.labels.map(l=>l.name)));

      - name: Check label & author
        id: gate
        run: |
          LABELS='${{ steps.pr.outputs.labels }}'
          AUTHOR='${{ steps.pr.outputs.author }}'
          echo "labels=$LABELS"
          echo "author=$AUTHOR"
          if [[ "$LABELS" != *automerge* ]]; then
            echo "no automerge label"; exit 0; fi
          if [[ "$AUTHOR" != "go2telegram" && "$GITHUB_ACTOR" != "github-actions[bot]" ]]; then
            echo "not trusted author"; exit 0; fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: refs/pull/${{ steps.prnum.outputs.number }}/head

      - name: Paths filter (risky changes)
        id: pf2
        uses: dorny/paths-filter@v3
        with:
          filters: |
            risky:
              - '.github/workflows/**'
              - 'Dockerfile'
              - 'requirements*.txt'
              - 'run.py'
              - 'app/main.py'
              - 'scripts/**'

      - name: Remove automerge label if risky
        if: steps.pf2.outputs.risky == 'true'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 'automerge'
          pull-request-number: ${{ steps.prnum.outputs.number }}

      - name: Auto-merge (CI completed successfully)
        if: steps.pf2.outputs.risky != 'true'
        uses: peter-evans/auto-merge@v3
        with:
          pull-request: ${{ steps.prnum.outputs.number }}
          merge-method: squash

      - name: Upload debug (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ github.workflow }}-${{ github.run_id }}
          path: |
            debug.log
          if-no-files-found: warn
