name: render-menu-map
on:
  push:
    paths:
      - "docs/*.mmd"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Install mermaid-cli
        run: npm i -g @mermaid-js/mermaid-cli@10

      - name: Render menu_map.mmd → SVG
        run: |
          npx @mermaid-js/mermaid-cli \
            -i docs/menu_map.mmd \
            -o docs/menu_map.svg \
            -b transparent -w 1400
          echo "Rendered docs/menu_map.svg"

      - name: Commit SVG if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/menu_map.svg
          git diff --cached --quiet || git commit -m "chore(docs): auto-render menu_map.svg from .mmd"
          git push
